<?php

class TransactionRecord {
	const HOUSE_PURCHASE = "HOUSE_PURCHASE";
	const HOUSE_RENT = "HOUSE_RENT";
	const HOUSE_SELL = "HOUSE_SELL";
	const HOUSE_DONATION = "HOUSE_DONATION";
	const HOUSE_BENEFITS = "HOUSE_BENEFITS";
	const HOUSE_UPGRADE = "HOUSE_UPGRADE";
	const MARKET_PURCHASE = "MARKET_PURCHASE";
	const MARKET_SELL = "MARKET_SELL";
	const ANONYMOUS_DONATION = "ANONYMOUS_DONATION";
	const REFER_FRIEND = "REFER_FRIEND";
	const PAY_DELAY = "PAY_DELAY";
}
